# 不要修改该文件，会自动生成，详见 https://gitlab.alibaba-inc.com/node/ci

stage:
  node-8-单元测试:
    env:
      image: 'aone-base/component-market_ide:20190521194519'
    plugin:
      -
        param:
          url: '${repo}'
          branch: '${branch}'
          path: '${source_root}'
          isDelGit: 'false'
        name: checkout
        pos: front
      -
        param:
          version: node-8
          source: '${source_root}'
        name: node_envs
        pos: front
    exec:
      - 'tnpm run ci && $PWD/node_modules/.bin/alicov-report'
pipeline:
  - 'node-8-单元测试'
